module.exports = Object.freeze({
  CAT1: 'CATEGORY_1',
  CAT2: 'CATEGORY_2',
  CAT3: 'CATEGORY_3',
  CAT4: 'CATEGORY_4',
  CAT5: 'CATEGORY_5',
  CAT6: 'CATEGORY_6',
  CAT7: 'CATEGORY_7',
  CAT8: 'CATEGORY_8',
  CAT9: 'CATEGORY_9',
  CAT10: 'CATEGORY_10',

  values: [
    'CATEGORY_1',
    'CATEGORY_2',
    'CATEGORY_3',
    'CATEGORY_4',
    'CATEGORY_5',
    'CATEGORY_6',
    'CATEGORY_7',
    'CATEGORY_8',
    'CATEGORY_9',
    'CATEGORY_10',
  ],
});
